apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-frontend
  namespace: bidly
  labels:
    app.kubernetes.io/name: auction-frontend
    app.kubernetes.io/version: main-8
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auction-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auction-frontend
        app.kubernetes.io/version: main-8
    spec:
      containers:
        - name: auction-frontend
          image: aididalam/bidly-frontend-auction:main-8
          env:
            - name: S3_PUBLIC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bidly-s3
                  key: s3-public-base-url
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
