apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: bidly
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      containers:
        - name: auth
          image: aididalam/bidly-auth:main-4
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: AUTH_SERVICE_PORT
              value: "8081"
            - name: AUTH_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bidly-auth-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bidly-auth-secrets
                  key: jwt-secret
            - name: JWT_EXPIRY
              value: 24h
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
