apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: bidly
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  selector:
    app.kubernetes.io/name: auth
  ports:
    - name: http
      port: 8081
      targetPort: http
